### ISSUE TITLE
IR170: Mouse move only on ~2/3 of my Screen

### ISSUE THREAD

**Issue by Mudspike9** [glenmurphy/fingers#13]
Hello
I use a IR170 (https://www.ultraleap.com/product/stereo-ir-170/) instead of the Leap Motion Controller.

It works, but if i point a finger on the left side, the mouse will be on ~1/3 in the middle of my screen.
What i do: I open the Ultraleap Tracker and move a finger to left side of the view. But i see that the cursur will not enter the first 1/3 of my monitor. On right side all works great.

I think that can be happen, because the Ir170 has 30° more Field of View(140×120° vs 170×170° )?

I looked at the code, but before i dig deeper, perhaps anyone can help me fast to point the right place?
Or any other hints

Thanks
Mudspike

**Comment by glenmurphy** [comment]
I'm also using an IR170 (which is what the Pimax hand tracking module is), so it shouldn't be that.

Do you get the issue you describe when DCS is open? The weirdest part of the code is from trying to compensate for how DCS maps mouse cursor position to its internal position - it tracks the DCS window and causes the position to scale and stop at certain points in order to get it right (and to stop your cursor accidentally clicking outside the DCS window).

Failing that, do you have multiple monitors? Fingers has only been tested on single-monitor systems, so there used to be some bugs in how it handled multiple monitors (scaling the input across the total resolution)

**Comment by Mudspike9** [comment]
I was in DCS i can't reach the left side of the cockpit, so i test it without DCS.
But the problem are gone! 
 i want to test your hint and  more errors at moment. Strange i have disconnect IR170 and start the tracker etc. 
But a reboot was the trick.

So thank you for your help and for finger at all, i will test more with it.

**Comment by glenmurphy** [comment]
The issue is (and I am daft for not realizing this earlier) the different horizontal FOVs of different headsets. Will add a FOV control.
